# Парсинг

In [4]:
import requests      # Библиотека для отправки запросов
import numpy as np   # Библиотека для матриц, векторов и линала
import pandas as pd  # Библиотека для табличек
import time          # Библиотека для тайм-менеджмента
from bs4 import BeautifulSoup
! pip install fake-useragent

from fake_useragent import UserAgent
UserAgent().chrome

In [132]:
# получим доступ к сайту ЦБ
url_USD = 'https://cbr.ru/currency_base/dynamics/?UniDbQuery.Posted=True&UniDbQuery.so=1&UniDbQuery.mode=1&UniDbQuery.date_req1=&UniDbQuery.date_req2=&UniDbQuery.VAL_NM_RQ=R01235&UniDbQuery.From=15.05.2015&UniDbQuery.To=15.05.2023'
otvet_USD = requests.get(url_USD, headers = {'User-Agent': UserAgent().chrome})

# распарсим страничку в дерево 
derevo_USD = BeautifulSoup(otvet_USD.content, 'html.parser')

# найдём нужную часть информации сайта
sth_USD = derevo_USD.find_all('td')

# сделаем список с курсом USD
rates_USD = []
dates_USD = []

for i in range(3, len(sth_USD), 3):
    rates_USD.append(sth_USD[i].text)
    
for i in range(1, len(sth_USD), 3):
    dates_USD.append(sth_USD[i].text)
    
print(rates_USD[:10], dates_USD[:10])

['77,2041', '75,8846', '76,6929', '76,8207', '78,6139', '79,3071', '79,9609', '80,5093', '81,5601', '81,6274'] ['13.05.2023', '12.05.2023', '11.05.2023', '06.05.2023', '05.05.2023', '04.05.2023', '03.05.2023', '29.04.2023', '28.04.2023', '27.04.2023']

In [136]:
# получим доступ к сайту ЦБ
url_EUR = 'https://cbr.ru/currency_base/dynamics/?UniDbQuery.Posted=True&UniDbQuery.so=1&UniDbQuery.mode=1&UniDbQuery.date_req1=&UniDbQuery.date_req2=&UniDbQuery.VAL_NM_RQ=R01239&UniDbQuery.From=15.05.2015&UniDbQuery.To=15.05.2023'
otvet_EUR = requests.get(url_EUR)

# распарсим страничку в дерево 
derevo_EUR = BeautifulSoup(otvet_EUR.content, 'html.parser')

# найдём нужную часть информации сайта
sth_EUR = derevo_EUR.find_all('td')

# сделаем список с курсом EUR
rates_EUR = []
dates_EUR = []

for i in range(3, len(sth_EUR), 3):
    rates_EUR.append(sth_EUR[i].text)
    
for i in range(1, len(sth_EUR), 3):    
    dates_EUR.append(sth_EUR[i].text)
    
print(rates_EUR[:10], dates_EUR[:10])

['84,2500', '82,8877', '84,1498', '84,9073', '86,9986', '87,5750', '87,6556', '88,3712', '90,2023', '90,1436'] ['13.05.2023', '12.05.2023', '11.05.2023', '06.05.2023', '05.05.2023', '04.05.2023', '03.05.2023', '29.04.2023', '28.04.2023', '27.04.2023']

In [137]:
# получим доступ к сайту ЦБ
url_GBP = 'https://cbr.ru/currency_base/dynamics/?UniDbQuery.Posted=True&UniDbQuery.so=1&UniDbQuery.mode=1&UniDbQuery.date_req1=&UniDbQuery.date_req2=&UniDbQuery.VAL_NM_RQ=R01035&UniDbQuery.From=15.05.2015&UniDbQuery.To=15.05.2023'
otvet_GBP = requests.get(url_GBP, headers = {'User-Agent': UserAgent().chrome})

# распарсим страничку в дерево 
derevo_GBP = BeautifulSoup(otvet_GBP.content, 'html.parser')

# найдём нужную часть информации сайта
sth_GBP = derevo_GBP.find_all('td')

# сделаем список с курсом GBP
rates_GBP = []
dates_GBP = []

for i in range(3, len(sth_GBP), 3):
    rates_GBP.append(sth_GBP[i].text)
    
for i in range(1, len(sth_GBP), 3):    
    dates_GBP.append(sth_GBP[i].text)
    
print(rates_GBP[:10], dates_GBP[:10])

['96,6827', '95,7512', '96,7251', '96,5790', '98,5268', '98,9118', '100,4789', '100,5883', '101,7218', '101,2343'] ['13.05.2023', '12.05.2023', '11.05.2023', '06.05.2023', '05.05.2023', '04.05.2023', '03.05.2023', '29.04.2023', '28.04.2023', '27.04.2023']

In [119]:
# получим доступ к сайту ЦБ
url_CNY = 'https://cbr.ru/currency_base/dynamics/?UniDbQuery.Posted=True&UniDbQuery.so=1&UniDbQuery.mode=1&UniDbQuery.date_req1=&UniDbQuery.date_req2=&UniDbQuery.VAL_NM_RQ=R01375&UniDbQuery.From=15.05.2015&UniDbQuery.To=15.05.2023'
otvet_CNY = requests.get(url_CNY, headers = {'User-Agent': UserAgent().chrome})

# распарсим страничку в дерево 
derevo_CNY = BeautifulSoup(otvet_CNY.content, 'html.parser')

# найдём нужную часть информации сайта
sth_CNY = derevo_CNY.find_all('td')

# сделаем список с курсом CNY
rates_CNY = []
dates_CNY = []

for i in range(3, len(sth_CNY), 3):
    rates_CNY.append(sth_CNY[i].text)
    
for i in range(1, len(sth_CNY), 3):    
    dates_CNY.append(sth_CNY[i].text)
    
print(rates_CNY[:10], dates_CNY[:10])

['11,0844', '10,9119', '11,0390', '11,1158', '11,3488', '11,4456', '11,4884', '11,5659', '11,7609', '11,7626'] ['13.05.2023', '12.05.2023', '11.05.2023', '06.05.2023', '05.05.2023', '04.05.2023', '03.05.2023', '29.04.2023', '28.04.2023', '27.04.2023']

In [120]:
# получим доступ к сайту ЦБ
url_JPY = 'https://cbr.ru/currency_base/dynamics/?UniDbQuery.Posted=True&UniDbQuery.so=1&UniDbQuery.mode=1&UniDbQuery.date_req1=&UniDbQuery.date_req2=&UniDbQuery.VAL_NM_RQ=R01820&UniDbQuery.From=15.05.2015&UniDbQuery.To=15.05.2023'
otvet_JPY = requests.get(url_JPY, headers = {'User-Agent': UserAgent().chrome})

# распарсим страничку в дерево 
derevo_JPY = BeautifulSoup(otvet_JPY.content, 'html.parser')

# найдём нужную часть информации сайта
sth_JPY = derevo_JPY.find_all('td')

# сделаем список с курсом CNY
rates_JPY = []
dates_JPY = []

for i in range(3, len(sth_JPY), 3):
    rates_JPY.append(sth_JPY[i].text)
    
for i in range(1, len(sth_JPY), 3):    
    dates_JPY.append(sth_JPY[i].text)
    
print(rates_JPY[:10], dates_JPY[:10])

['57,3795', '56,5881', '56,7465', '55,8615', '57,1654', '57,6695', '58,1449', '60,0592', '61,0160', '61,0344'] ['13.05.2023', '12.05.2023', '11.05.2023', '06.05.2023', '05.05.2023', '04.05.2023', '03.05.2023', '29.04.2023', '28.04.2023', '27.04.2023']

In [134]:
# упакуем все данные в датафрейм
rates = pd.DataFrame({'Дата': dates_USD, 
                      'Доллар США': rates_USD, 
                      'Евро': rates_EUR,
                      'Фунт стерлингов': rates_GBP,
                      'Китайский юань': rates_CNY,
                      'Японская йена': rates_JPY})
rates

,Дата,Доллар США,Евро,Фунт стерлингов,Китайский юань,Японская йена
0,13.05.2023,"77,2041","84,2500","96,6827","11,0844","57,3795"
1,12.05.2023,"75,8846","82,8877","95,7512","10,9119","56,5881"
2,11.05.2023,"76,6929","84,1498","96,7251","11,0390","56,7465"
3,06.05.2023,"76,8207","84,9073","96,5790","11,1158","55,8615"
4,05.05.2023,"78,6139","86,9986","98,5268","11,3488","57,1654"
...,...,...,...,...,...,...
1968,21.05.2015,"49,7919","55,2441","77,1774","80,2603","41,1622"
1969,20.05.2015,"49,1777","55,1085","76,5943","79,2307","40,9797"
1970,19.05.2015,"49,2175","56,1030","77,0992","79,3280","41,1260"
1971,16.05.2015,"50,0115","56,9881","78,8431","80,5805","41,8436"
1972,15.05.2015,"50,0774","57,1383","78,9420","80,7505","42,0148"

# Предобработка

In [139]:
rates.shape

(1973, 6)

# Черновик

In [1]:
import requests
data = requests.get('https://www.cbr-xml-daily.ru/daily_json.js').json()
print (data['Valute']['USD']['Value'])

77.2041

In [2]:
data

{'Date': '2023-05-13T11:30:00+03:00',
 'PreviousDate': '2023-05-12T11:30:00+03:00',
 'PreviousURL': '//www.cbr-xml-daily.ru/archive/2023/05/12/daily_json.js',
 'Timestamp': '2023-05-15T13:00:00+03:00',
 'Valute': {'AUD': {'ID': 'R01010',
   'NumCode': '036',
   'CharCode': 'AUD',
   'Nominal': 1,
   'Name': 'Австралийский доллар',
   'Value': 51.6495,
   'Previous': 51.4118},
  'AZN': {'ID': 'R01020A',
   'NumCode': '944',
   'CharCode': 'AZN',
   'Nominal': 1,
   'Name': 'Азербайджанский манат',
   'Value': 45.4142,
   'Previous': 44.638},
  'GBP': {'ID': 'R01035',
   'NumCode': '826',
   'CharCode': 'GBP',
   'Nominal': 1,
   'Name': 'Фунт стерлингов Соединенного королевства',
   'Value': 96.6827,
   'Previous': 95.7512},
  'AMD': {'ID': 'R01060',
   'NumCode': '051',
   'CharCode': 'AMD',
   'Nominal': 100,
   'Name': 'Армянских драмов',
   'Value': 19.9814,
   'Previous': 19.6424},
  'BYN': {'ID': 'R01090B',
   'NumCode': '933',
   'CharCode': 'BYN',
   'Nominal': 1,
   'Name': 'Белорусский рубль',
   'Value': 27.22,
   'Previous': 27.1045},
  'BGN': {'ID': 'R01100',
   'NumCode': '975',
   'CharCode': 'BGN',
   'Nominal': 1,
   'Name': 'Болгарский лев',
   'Value': 43.1452,
   'Previous': 42.4838},
  'BRL': {'ID': 'R01115',
   'NumCode': '986',
   'CharCode': 'BRL',
   'Nominal': 1,
   'Name': 'Бразильский реал',
   'Value': 15.5362,
   'Previous': 15.3166},
  'HUF': {'ID': 'R01135',
   'NumCode': '348',
   'CharCode': 'HUF',
   'Nominal': 100,
   'Name': 'Венгерских форинтов',
   'Value': 22.6764,
   'Previous': 22.3624},
  'VND': {'ID': 'R01150',
   'NumCode': '704',
   'CharCode': 'VND',
   'Nominal': 10000,
   'Name': 'Вьетнамских донгов',
   'Value': 32.6582,
   'Previous': 32.111},
  'HKD': {'ID': 'R01200',
   'NumCode': '344',
   'CharCode': 'HKD',
   'Nominal': 10,
   'Name': 'Гонконгских долларов',
   'Value': 98.6256,
   'Previous': 96.9895},
  'GEL': {'ID': 'R01210',
   'NumCode': '981',
   'CharCode': 'GEL',
   'Nominal': 1,
   'Name': 'Грузинский лари',
   'Value': 30.3261,
   'Previous': 30.001},
  'DKK': {'ID': 'R01215',
   'NumCode': '208',
   'CharCode': 'DKK',
   'Nominal': 1,
   'Name': 'Датская крона',
   'Value': 11.3292,
   'Previous': 11.1569},
  'AED': {'ID': 'R01230',
   'NumCode': '784',
   'CharCode': 'AED',
   'Nominal': 1,
   'Name': 'Дирхам ОАЭ',
   'Value': 21.0239,
   'Previous': 20.6646},
  'USD': {'ID': 'R01235',
   'NumCode': '840',
   'CharCode': 'USD',
   'Nominal': 1,
   'Name': 'Доллар США',
   'Value': 77.2041,
   'Previous': 75.8846},
  'EUR': {'ID': 'R01239',
   'NumCode': '978',
   'CharCode': 'EUR',
   'Nominal': 1,
   'Name': 'Евро',
   'Value': 84.25,
   'Previous': 82.8877},
  'EGP': {'ID': 'R01240',
   'NumCode': '818',
   'CharCode': 'EGP',
   'Nominal': 10,
   'Name': 'Египетских фунтов',
   'Value': 24.9855,
   'Previous': 24.5585},
  'INR': {'ID': 'R01270',
   'NumCode': '356',
   'CharCode': 'INR',
   'Nominal': 100,
   'Name': 'Индийских рупий',
   'Value': 94.4563,
   'Previous': 92.8419},
  'IDR': {'ID': 'R01280',
   'NumCode': '360',
   'CharCode': 'IDR',
   'Nominal': 10000,
   'Name': 'Индонезийских рупий',
   'Value': 52.4413,
   'Previous': 51.4611},
  'KZT': {'ID': 'R01335',
   'NumCode': '398',
   'CharCode': 'KZT',
   'Nominal': 100,
   'Name': 'Казахстанских тенге',
   'Value': 17.3797,
   'Previous': 17.085},
  'CAD': {'ID': 'R01350',
   'NumCode': '124',
   'CharCode': 'CAD',
   'Nominal': 1,
   'Name': 'Канадский доллар',
   'Value': 57.2858,
   'Previous': 56.7361},
  'QAR': {'ID': 'R01355',
   'NumCode': '634',
   'CharCode': 'QAR',
   'Nominal': 1,
   'Name': 'Катарский риал',
   'Value': 21.2099,
   'Previous': 20.8474},
  'KGS': {'ID': 'R01370',
   'NumCode': '417',
   'CharCode': 'KGS',
   'Nominal': 100,
   'Name': 'Киргизских сомов',
   'Value': 88.4354,
   'Previous': 86.9198},
  'CNY': {'ID': 'R01375',
   'NumCode': '156',
   'CharCode': 'CNY',
   'Nominal': 1,
   'Name': 'Китайский юань',
   'Value': 11.0844,
   'Previous': 10.9119},
  'MDL': {'ID': 'R01500',
   'NumCode': '498',
   'CharCode': 'MDL',
   'Nominal': 10,
   'Name': 'Молдавских леев',
   'Value': 43.3641,
   'Previous': 42.5751},
  'NZD': {'ID': 'R01530',
   'NumCode': '554',
   'CharCode': 'NZD',
   'Nominal': 1,
   'Name': 'Новозеландский доллар',
   'Value': 48.4842,
   'Previous': 48.3688},
  'NOK': {'ID': 'R01535',
   'NumCode': '578',
   'CharCode': 'NOK',
   'Nominal': 10,
   'Name': 'Норвежских крон',
   'Value': 72.2777,
   'Previous': 71.9865},
  'PLN': {'ID': 'R01565',
   'NumCode': '985',
   'CharCode': 'PLN',
   'Nominal': 1,
   'Name': 'Польский злотый',
   'Value': 18.5484,
   'Previous': 18.3371},
  'RON': {'ID': 'R01585F',
   'NumCode': '946',
   'CharCode': 'RON',
   'Nominal': 1,
   'Name': 'Румынский лей',
   'Value': 17.0707,
   'Previous': 16.8221},
  'XDR': {'ID': 'R01589',
   'NumCode': '960',
   'CharCode': 'XDR',
   'Nominal': 1,
   'Name': 'СДР (специальные права заимствования)',
   'Value': 103.9615,
   'Previous': 102.2742},
  'SGD': {'ID': 'R01625',
   'NumCode': '702',
   'CharCode': 'SGD',
   'Nominal': 1,
   'Name': 'Сингапурский доллар',
   'Value': 57.9784,
   'Previous': 57.2412},
  'TJS': {'ID': 'R01670',
   'NumCode': '972',
   'CharCode': 'TJS',
   'Nominal': 10,
   'Name': 'Таджикских сомони',
   'Value': 70.7425,
   'Previous': 69.5315},
  'THB': {'ID': 'R01675',
   'NumCode': '764',
   'CharCode': 'THB',
   'Nominal': 10,
   'Name': 'Таиландских батов',
   'Value': 22.7901,
   'Previous': 22.5401},
  'TRY': {'ID': 'R01700J',
   'NumCode': '949',
   'CharCode': 'TRY',
   'Nominal': 10,
   'Name': 'Турецких лир',
   'Value': 39.4775,
   'Previous': 38.8534},
  'TMT': {'ID': 'R01710A',
   'NumCode': '934',
   'CharCode': 'TMT',
   'Nominal': 1,
   'Name': 'Новый туркменский манат',
   'Value': 22.0583,
   'Previous': 21.6813},
  'UZS': {'ID': 'R01717',
   'NumCode': '860',
   'CharCode': 'UZS',
   'Nominal': 10000,
   'Name': 'Узбекских сумов',
   'Value': 67.3389,
   'Previous': 66.257},
  'UAH': {'ID': 'R01720',
   'NumCode': '980',
   'CharCode': 'UAH',
   'Nominal': 10,
   'Name': 'Украинских гривен',
   'Value': 20.9043,
   'Previous': 20.5459},
  'CZK': {'ID': 'R01760',
   'NumCode': '203',
   'CharCode': 'CZK',
   'Nominal': 10,
   'Name': 'Чешских крон',
   'Value': 35.9239,
   'Previous': 35.4866},
  'SEK': {'ID': 'R01770',
   'NumCode': '752',
   'CharCode': 'SEK',
   'Nominal': 10,
   'Name': 'Шведских крон',
   'Value': 74.8915,
   'Previous': 73.9148},
  'CHF': {'ID': 'R01775',
   'NumCode': '756',
   'CharCode': 'CHF',
   'Nominal': 1,
   'Name': 'Швейцарский франк',
   'Value': 86.5614,
   'Previous': 84.8062},
  'RSD': {'ID': 'R01805F',
   'NumCode': '941',
   'CharCode': 'RSD',
   'Nominal': 100,
   'Name': 'Сербских динаров',
   'Value': 71.9023,
   'Previous': 71.0387},
  'ZAR': {'ID': 'R01810',
   'NumCode': '710',
   'CharCode': 'ZAR',
   'Nominal': 10,
   'Name': 'Южноафриканских рэндов',
   'Value': 39.8438,
   'Previous': 40.0736},
  'KRW': {'ID': 'R01815',
   'NumCode': '410',
   'CharCode': 'KRW',
   'Nominal': 1000,
   'Name': 'Вон Республики Корея',
   'Value': 57.8525,
   'Previous': 57.2153},
  'JPY': {'ID': 'R01820',
   'NumCode': '392',
   'CharCode': 'JPY',
   'Nominal': 100,
   'Name': 'Японских иен',
   'Value': 57.3795,
   'Previous': 56.5881}}}

In [5]:
data_pd = pd.DataFrame(data)
data_pd

,Date,PreviousDate,PreviousURL,Timestamp,Valute
AED,2023-05-13T11:30:00+03:00,2023-05-12T11:30:00+03:00,//www.cbr-xml-daily.ru/archive/2023/05/12/dail...,2023-05-15T13:00:00+03:00,"{'ID': 'R01230', 'NumCode': '784', 'CharCode':..."
AMD,2023-05-13T11:30:00+03:00,2023-05-12T11:30:00+03:00,//www.cbr-xml-daily.ru/archive/2023/05/12/dail...,2023-05-15T13:00:00+03:00,"{'ID': 'R01060', 'NumCode': '051', 'CharCode':..."
AUD,2023-05-13T11:30:00+03:00,2023-05-12T11:30:00+03:00,//www.cbr-xml-daily.ru/archive/2023/05/12/dail...,2023-05-15T13:00:00+03:00,"{'ID': 'R01010', 'NumCode': '036', 'CharCode':..."
AZN,2023-05-13T11:30:00+03:00,2023-05-12T11:30:00+03:00,//www.cbr-xml-daily.ru/archive/2023/05/12/dail...,2023-05-15T13:00:00+03:00,"{'ID': 'R01020A', 'NumCode': '944', 'CharCode'..."
BGN,2023-05-13T11:30:00+03:00,2023-05-12T11:30:00+03:00,//www.cbr-xml-daily.ru/archive/2023/05/12/dail...,2023-05-15T13:00:00+03:00,"{'ID': 'R01100', 'NumCode': '975', 'CharCode':..."
BRL,2023-05-13T11:30:00+03:00,2023-05-12T11:30:00+03:00,//www.cbr-xml-daily.ru/archive/2023/05/12/dail...,2023-05-15T13:00:00+03:00,"{'ID': 'R01115', 'NumCode': '986', 'CharCode':..."
BYN,2023-05-13T11:30:00+03:00,2023-05-12T11:30:00+03:00,//www.cbr-xml-daily.ru/archive/2023/05/12/dail...,2023-05-15T13:00:00+03:00,"{'ID': 'R01090B', 'NumCode': '933', 'CharCode'..."
CAD,2023-05-13T11:30:00+03:00,2023-05-12T11:30:00+03:00,//www.cbr-xml-daily.ru/archive/2023/05/12/dail...,2023-05-15T13:00:00+03:00,"{'ID': 'R01350', 'NumCode': '124', 'CharCode':..."
CHF,2023-05-13T11:30:00+03:00,2023-05-12T11:30:00+03:00,//www.cbr-xml-daily.ru/archive/2023/05/12/dail...,2023-05-15T13:00:00+03:00,"{'ID': 'R01775', 'NumCode': '756', 'CharCode':..."
CNY,2023-05-13T11:30:00+03:00,2023-05-12T11:30:00+03:00,//www.cbr-xml-daily.ru/archive/2023/05/12/dail...,2023-05-15T13:00:00+03:00,"{'ID': 'R01375', 'NumCode': '156', 'CharCode':..."
CZK,2023-05-13T11:30:00+03:00,2023-05-12T11:30:00+03:00,//www.cbr-xml-daily.ru/archive/2023/05/12/dail...,2023-05-15T13:00:00+03:00,"{'ID': 'R01760', 'NumCode': '203', 'CharCode':..."
DKK,2023-05-13T11:30:00+03:00,2023-05-12T11:30:00+03:00,//www.cbr-xml-daily.ru/archive/2023/05/12/dail...,2023-05-15T13:00:00+03:00,"{'ID': 'R01215', 'NumCode': '208', 'CharCode':..."
EGP,2023-05-13T11:30:00+03:00,2023-05-12T11:30:00+03:00,//www.cbr-xml-daily.ru/archive/2023/05/12/dail...,2023-05-15T13:00:00+03:00,"{'ID': 'R01240', 'NumCode': '818', 'CharCode':..."
EUR,2023-05-13T11:30:00+03:00,2023-05-12T11:30:00+03:00,//www.cbr-xml-daily.ru/archive/2023/05/12/dail...,2023-05-15T13:00:00+03:00,"{'ID': 'R01239', 'NumCode': '978', 'CharCode':..."
GBP,2023-05-13T11:30:00+03:00,2023-05-12T11:30:00+03:00,//www.cbr-xml-daily.ru/archive/2023/05/12/dail...,2023-05-15T13:00:00+03:00,"{'ID': 'R01035', 'NumCode': '826', 'CharCode':..."
GEL,2023-05-13T11:30:00+03:00,2023-05-12T11:30:00+03:00,//www.cbr-xml-daily.ru/archive/2023/05/12/dail...,2023-05-15T13:00:00+03:00,"{'ID': 'R01210', 'NumCode': '981', 'CharCode':..."
HKD,2023-05-13T11:30:00+03:00,2023-05-12T11:30:00+03:00,//www.cbr-xml-daily.ru/archive/2023/05/12/dail...,2023-05-15T13:00:00+03:00,"{'ID': 'R01200', 'NumCode': '344', 'CharCode':..."
HUF,2023-05-13T11:30:00+03:00,2023-05-12T11:30:00+03:00,//www.cbr-xml-daily.ru/archive/2023/05/12/dail...,2023-05-15T13:00:00+03:00,"{'ID': 'R01135', 'NumCode': '348', 'CharCode':..."
IDR,2023-05-13T11:30:00+03:00,2023-05-12T11:30:00+03:00,//www.cbr-xml-daily.ru/archive/2023/05/12/dail...,2023-05-15T13:00:00+03:00,"{'ID': 'R01280', 'NumCode': '360', 'CharCode':..."
INR,2023-05-13T11:30:00+03:00,2023-05-12T11:30:00+03:00,//www.cbr-xml-daily.ru/archive/2023/05/12/dail...,2023-05-15T13:00:00+03:00,"{'ID': 'R01270', 'NumCode': '356', 'CharCode':..."
JPY,2023-05-13T11:30:00+03:00,2023-05-12T11:30:00+03:00,//www.cbr-xml-daily.ru/archive/2023/05/12/dail...,2023-05-15T13:00:00+03:00,"{'ID': 'R01820', 'NumCode': '392', 'CharCode':..."
KGS,2023-05-13T11:30:00+03:00,2023-05-12T11:30:00+03:00,//www.cbr-xml-daily.ru/archive/2023/05/12/dail...,2023-05-15T13:00:00+03:00,"{'ID': 'R01370', 'NumCode': '417', 'CharCode':..."
KRW,2023-05-13T11:30:00+03:00,2023-05-12T11:30:00+03:00,//www.cbr-xml-daily.ru/archive/2023/05/12/dail...,2023-05-15T13:00:00+03:00,"{'ID': 'R01815', 'NumCode': '410', 'CharCode':..."
KZT,2023-05-13T11:30:00+03:00,2023-05-12T11:30:00+03:00,//www.cbr-xml-daily.ru/archive/2023/05/12/dail...,2023-05-15T13:00:00+03:00,"{'ID': 'R01335', 'NumCode': '398', 'CharCode':..."
MDL,2023-05-13T11:30:00+03:00,2023-05-12T11:30:00+03:00,//www.cbr-xml-daily.ru/archive/2023/05/12/dail...,2023-05-15T13:00:00+03:00,"{'ID': 'R01500', 'NumCode': '498', 'CharCode':..."
NOK,2023-05-13T11:30:00+03:00,2023-05-12T11:30:00+03:00,//www.cbr-xml-daily.ru/archive/2023/05/12/dail...,2023-05-15T13:00:00+03:00,"{'ID': 'R01535', 'NumCode': '578', 'CharCode':..."
NZD,2023-05-13T11:30:00+03:00,2023-05-12T11:30:00+03:00,//www.cbr-xml-daily.ru/archive/2023/05/12/dail...,2023-05-15T13:00:00+03:00,"{'ID': 'R01530', 'NumCode': '554', 'CharCode':..."
PLN,2023-05-13T11:30:00+03:00,2023-05-12T11:30:00+03:00,//www.cbr-xml-daily.ru/archive/2023/05/12/dail...,2023-05-15T13:00:00+03:00,"{'ID': 'R01565', 'NumCode': '985', 'CharCode':..."
QAR,2023-05-13T11:30:00+03:00,2023-05-12T11:30:00+03:00,//www.cbr-xml-daily.ru/archive/2023/05/12/dail...,2023-05-15T13:00:00+03:00,"{'ID': 'R01355', 'NumCode': '634', 'CharCode':..."
RON,2023-05-13T11:30:00+03:00,2023-05-12T11:30:00+03:00,//www.cbr-xml-daily.ru/archive/2023/05/12/dail...,2023-05-15T13:00:00+03:00,"{'ID': 'R01585F', 'NumCode': '946', 'CharCode'..."
RSD,2023-05-13T11:30:00+03:00,2023-05-12T11:30:00+03:00,//www.cbr-xml-daily.ru/archive/2023/05/12/dail...,2023-05-15T13:00:00+03:00,"{'ID': 'R01805F', 'NumCode': '941', 'CharCode'..."
SEK,2023-05-13T11:30:00+03:00,2023-05-12T11:30:00+03:00,//www.cbr-xml-daily.ru/archive/2023/05/12/dail...,2023-05-15T13:00:00+03:00,"{'ID': 'R01770', 'NumCode': '752', 'CharCode':..."
SGD,2023-05-13T11:30:00+03:00,2023-05-12T11:30:00+03:00,//www.cbr-xml-daily.ru/archive/2023/05/12/dail...,2023-05-15T13:00:00+03:00,"{'ID': 'R01625', 'NumCode': '702', 'CharCode':..."
THB,2023-05-13T11:30:00+03:00,2023-05-12T11:30:00+03:00,//www.cbr-xml-daily.ru/archive/2023/05/12/dail...,2023-05-15T13:00:00+03:00,"{'ID': 'R01675', 'NumCode': '764', 'CharCode':..."
TJS,2023-05-13T11:30:00+03:00,2023-05-12T11:30:00+03:00,//www.cbr-xml-daily.ru/archive/2023/05/12/dail...,2023-05-15T13:00:00+03:00,"{'ID': 'R01670', 'NumCode': '972', 'CharCode':..."
TMT,2023-05-13T11:30:00+03:00,2023-05-12T11:30:00+03:00,//www.cbr-xml-daily.ru/archive/2023/05/12/dail...,2023-05-15T13:00:00+03:00,"{'ID': 'R01710A', 'NumCode': '934', 'CharCode'..."
TRY,2023-05-13T11:30:00+03:00,2023-05-12T11:30:00+03:00,//www.cbr-xml-daily.ru/archive/2023/05/12/dail...,2023-05-15T13:00:00+03:00,"{'ID': 'R01700J', 'NumCode': '949', 'CharCode'..."
UAH,2023-05-13T11:30:00+03:00,2023-05-12T11:30:00+03:00,//www.cbr-xml-daily.ru/archive/2023/05/12/dail...,2023-05-15T13:00:00+03:00,"{'ID': 'R01720', 'NumCode': '980', 'CharCode':..."
USD,2023-05-13T11:30:00+03:00,2023-05-12T11:30:00+03:00,//www.cbr-xml-daily.ru/archive/2023/05/12/dail...,2023-05-15T13:00:00+03:00,"{'ID': 'R01235', 'NumCode': '840', 'CharCode':..."
UZS,2023-05-13T11:30:00+03:00,2023-05-12T11:30:00+03:00,//www.cbr-xml-daily.ru/archive/2023/05/12/dail...,2023-05-15T13:00:00+03:00,"{'ID': 'R01717', 'NumCode': '860', 'CharCode':..."
VND,2023-05-13T11:30:00+03:00,2023-05-12T11:30:00+03:00,//www.cbr-xml-daily.ru/archive/2023/05/12/dail...,2023-05-15T13:00:00+03:00,"{'ID': 'R01150', 'NumCode': '704', 'CharCode':..."
XDR,2023-05-13T11:30:00+03:00,2023-05-12T11:30:00+03:00,//www.cbr-xml-daily.ru/archive/2023/05/12/dail...,2023-05-15T13:00:00+03:00,"{'ID': 'R01589', 'NumCode': '960', 'CharCode':..."
ZAR,2023-05-13T11:30:00+03:00,2023-05-12T11:30:00+03:00,//www.cbr-xml-daily.ru/archive/2023/05/12/dail...,2023-05-15T13:00:00+03:00,"{'ID': 'R01810', 'NumCode': '710', 'CharCode':..."

In [8]:
! pip install fake-useragent

from fake_useragent import UserAgent
UserAgent().chrome

Collecting fake-useragent
  Downloading fake_useragent-1.1.3-py3-none-any.whl (50 kB)
Collecting importlib-resources>=5.0
  Downloading importlib_resources-5.12.0-py3-none-any.whl (36 kB)
Requirement already satisfied: zipp>=3.1.0 in c:\programdata\anaconda3\lib\site-packages (from importlib-resources>=5.0->fake-useragent) (3.6.0)
Installing collected packages: importlib-resources, fake-useragent
Successfully installed fake-useragent-1.1.3 importlib-resources-5.12.0

'Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US) AppleWebKit/533.2 (KHTML, like Gecko) Chrome/6.0'

In [9]:
page_link = 'https://cbr.ru/currency_base/dynamics/?UniDbQuery.Posted=True&UniDbQuery.so=1&UniDbQuery.mode=1&UniDbQuery.date_req1=&UniDbQuery.date_req2=&UniDbQuery.VAL_NM_RQ=R01235&UniDbQuery.From=10.05.2023&UniDbQuery.To=15.05.2023'
response = requests.get(page_link, headers={'User-Agent': UserAgent().chrome})
response

In [11]:
response.text[:1000]

'\r\n<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    \r\n\r\n<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />\r\n<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">\r\n<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">\r\n<meta name="format-detection" content="telephone=no" />\r\n<meta name="zoom:lang" content="ru" />\r\n<title>Динамика официального курса заданной валюты | Банк России</title>\r\n\r\n\r\n\r\n    <meta property="og:image" content="/common/images/share-1.jpg" />\r\n\r\n    \r\n\r\n\r\n      <link rel="stylesheet" type="text/css" href="/common/libs/jquery-ui/jquery-ui.min.css?v=v599209514" media="all">\r\n\r\n      <!--[if IE 9]><link rel="stylesheet" type="text/css" href="/common/style/main-ie9.css?v=v3063901475" media="all"><![endif]-->\r\n\r\n      <!--[if gt IE 9]><!--><link rel="stylesheet" type="text/css" href="/common/style/main.min.css?v=v937190578" media="all"><!--<![endif]-->\r\n\r\n\r\n    <script type="text/javascript" src="/common/libs/jquery-3.6.1.min'

In [112]:
# распарсили страничку в дерево 
tree = BeautifulSoup(response.content, 'html.parser')

In [14]:
tree.title.text.strip()

'Динамика официального курса заданной валюты | Банк России'

In [32]:
tree.main.div.div.div.div

<div class="breadcrumbs">
<div class="breadcrumbs_item"><a class="breadcrumbs_home" href="/"></a></div>
<div class="breadcrumbs_item">
<a href="/hd_base/"><!--noindex-->Базы данных<!--/noindex--></a>
</div>
<div class="breadcrumbs_item">
<a href="/currency_base/"><!--noindex-->База данных по курсам валют<!--/noindex--></a>
</div>
</div>

In [52]:
books = tree.find_all('table', {'class' : 'data'})
books[0]

<table class="data">
<tr>
<td colspan="3">
<h3>Доллар США</h3>
</td>
</tr>
<tr>
<th><a class="pseudo" data-sort="0">Дата</a><font size="1"> ▼</font>
</th>
<th>Единиц</th>
<th>Курс</th>
</tr>
<tr>
<td>13.05.2023</td>
<td>1</td>
<td>77,2041</td>
</tr>
<tr>
<td>12.05.2023</td>
<td>1</td>
<td>75,8846</td>
</tr>
<tr>
<td>11.05.2023</td>
<td>1</td>
<td>76,6929</td>
</tr>
</table>

In [53]:
hz = tree.find_all('td')
hz

[<td colspan="3">
 <h3>Доллар США</h3>
 </td>,
 <td>13.05.2023</td>,
 <td>1</td>,
 <td>77,2041</td>,
 <td>12.05.2023</td>,
 <td>1</td>,
 <td>75,8846</td>,
 <td>11.05.2023</td>,
 <td>1</td>,
 <td>76,6929</td>]

In [54]:
a = books[0].find_all('td')
a

[<td colspan="3">
 <h3>Доллар США</h3>
 </td>,
 <td>13.05.2023</td>,
 <td>1</td>,
 <td>77,2041</td>,
 <td>12.05.2023</td>,
 <td>1</td>,
 <td>75,8846</td>,
 <td>11.05.2023</td>,
 <td>1</td>,
 <td>76,6929</td>]

In [58]:
type(a)

bs4.element.ResultSet

In [64]:
a[3]

In [79]:
infa = []

for i in range(3, len(a), 3):
    h = a[i].text
    infa.append(h)
    print(h)
infa

77,2041
75,8846
76,6929

['77,2041', '75,8846', '76,6929']

In [80]:
pd.DataFrame(infa)

         0
0  77,2041
1  75,8846
2  76,6929

In [55]:
books[0].find_all('td')[3].text

'77,2041'

In [49]:
infa = [ ]
    
for book in books: 
    infa.append({'price': for i in range(3, len(a), 3):
    print(a[i].text)})

    
    
infa

[{'price': '77,2041'}]

In [81]:
url = 'https://cbr.ru/currency_base/dynamics/?UniDbQuery.Posted=True&UniDbQuery.so=1&UniDbQuery.mode=1&UniDbQuery.date_req1=&UniDbQuery.date_req2=&UniDbQuery.VAL_NM_RQ=R01235&UniDbQuery.From=15.05.2020&UniDbQuery.To=15.05.2023'
otvet = requests.get(url, headers = {'User-Agent': UserAgent().chrome})
otvet

In [82]:
# распарсили страничку в дерево 
derevo = BeautifulSoup(otvet.content, 'html.parser')

In [86]:
sth = derevo.find_all('td')
sth[:10]

[<td colspan="3">
 <h3>Доллар США</h3>
 </td>,
 <td>13.05.2023</td>,
 <td>1</td>,
 <td>77,2041</td>,
 <td>12.05.2023</td>,
 <td>1</td>,
 <td>75,8846</td>,
 <td>11.05.2023</td>,
 <td>1</td>,
 <td>76,6929</td>]

In [91]:
dates = []
rates = []
        
for i in range(1, len(sth), 3):    
    dates.append(sth[i].text)
    
for i in range(3, len(sth), 3):
    rates.append(sth[i].text)
    
print(dates[:10], rates[:10])

['13.05.2023', '12.05.2023', '11.05.2023', '06.05.2023', '05.05.2023', '04.05.2023', '03.05.2023', '29.04.2023', '28.04.2023', '27.04.2023'] ['77,2041', '75,8846', '76,6929', '76,8207', '78,6139', '79,3071', '79,9609', '80,5093', '81,5601', '81,6274']

In [92]:
rates = pd.DataFrame(dates, rates)
rates

                  0
77,2041  13.05.2023
75,8846  12.05.2023
76,6929  11.05.2023
76,8207  06.05.2023
78,6139  05.05.2023
...             ...
72,3381  21.05.2020
72,3918  20.05.2020
72,9798  19.05.2020
73,2056  16.05.2020
73,9298  15.05.2020

[742 rows x 1 columns]

In [105]:
def get_rates(r):
    # получим доступ к сайту ЦБ
    url_USD = 'https://cbr.ru/currency_base/dynamics/?UniDbQuery.Posted=True&UniDbQuery.so=1&UniDbQuery.mode=1&UniDbQuery.date_req1=&UniDbQuery.date_req2=&UniDbQuery.VAL_NM_RQ={}.From=15.05.2015&UniDbQuery.To=15.05.2023'.format(r)
    otvet_USD = requests.get(url_USD, headers = {'User-Agent': UserAgent().chrome})

    # распарсим страничку в дерево 
    derevo_USD = BeautifulSoup(otvet_USD.content, 'html.parser')

    # найдём нужную часть информации сайта
    sth_USD = derevo.find_all('td')

    # сделаем список с курсом USD
    rates_USD = []
    dates_USD = []

    for i in range(3, len(sth_USD), 3):
        rates_USD.append(sth_USD[i].text)

    for i in range(1, len(sth_USD), 3):    
        dates_USD.append(sth_USD[i].text)
    
rates_USD[:10]

['77,2041',
 '75,8846',
 '76,6929',
 '76,8207',
 '78,6139',
 '79,3071',
 '79,9609',
 '80,5093',
 '81,5601',
 '81,6274']

In [107]:
infa = []
a = ['R01235&UniDbQuery']

for r in a:
    infa.extend(get_rates(r))

TypeError: 'NoneType' object is not iterable

In [96]:
dates_USD[:10]

['13.05.2023',
 '12.05.2023',
 '11.05.2023',
 '06.05.2023',
 '05.05.2023',
 '04.05.2023',
 '03.05.2023',
 '29.04.2023',
 '28.04.2023',
 '27.04.2023']